server:
  port: 9093

logging:
  level:
    org.springframework.web: DEBUG

spring:
  jpa:
    show-sql: true
    properties:
      hibernate: 
        format_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accessories?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
#  data:
#    rest:
#      base-path: /api
      
